# Generated by Django 5.2 on 2025-05-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_doctor_available_days'),
        ('Caregivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caregiver',
            unique_together={('caregiver', 'patient')},
        ),
    ]
