# Generated by Django 5.2 on 2025-05-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0002_alter_doctor_available_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diastolic_bp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_oxygen', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.userprofile')),
            ],
        ),
    ]
