# Generated by Django 5.2 on 2026-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='blood_oxygen',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='temperature',
        ),
        migrations.AddField(
            model_name='vital',
            name='body_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vital',
            name='edema',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='vital',
            name='shortness_of_breath',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
