# Generated by Django 5.2 on 2026-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitals', '0002_remove_vital_blood_oxygen_remove_vital_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='heart_rate',
            field=models.IntegerField(default=70),
        ),
    ]
