# Generated by Django 5.2 on 2026-02-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_doctor_available_days'),
        ('Caregivers', '0002_alter_caregiver_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caregiver',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiver',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Authentication.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='caregiver',
            unique_together={('patient', 'email')},
        ),
    ]
