# Generated by Django 5.2 on 2026-02-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caregivers', '0003_alter_caregiver_unique_together_caregiver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
